sudo: required

language: python

env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

services:
  - docker

cache:
  directories:
    - "$HOME/google-cloud-sdk"

before_install:
  # Install gcloud
  # From https://stackoverflow.com/questions/38762590/how-to-install-google-cloud-sdk-on-travis
  - export BOTO_CONFIG=/dev/null
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then
      rm -rf $HOME/google-cloud-sdk;
      curl https://sdk.cloud.google.com | bash;
    fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud version

install:
  - pip install jsonschema
  - pip install git+https://github.com/flywheel-io/gears.git

script:
  - if [ -z "$TRAVIS_PULL_REQUEST_BRANCH" ]; then
      export EXCHANGE_BRANCH=$TRAVIS_BRANCH;
    else
      export EXCHANGE_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH;
    fi
  - git remote add origin $GIT_REMOTE
  - git fetch
  - git checkout $GIT_BRANCH
  - travis_wait 1440 bin/process-manifests.sh "$EXCHANGE_BRANCH"



